# Generated by Django 5.0.3 on 2024-04-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_remove_news_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='photo',
            field=models.ImageField(null=True, upload_to='news/'),
        ),
    ]
